version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
