name: Build and Push Backend Docker Image

on:
  push:
    branches:
      - main # trigger workflow when there is change in dev branch
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    # Build, tag, and push the backend image
    - name: Build and push backend Docker image
      run: |
        docker build -t saideepsamineni/sproute-connect:backend-image ./backend
        docker push saideepsamineni/sproute-connect:backend-image